"""Add meta_data column to workspaces table

Revision ID: 0a5012b28b89
Revises: 65ce37c43657
Create Date: 2025-08-22 23:34:19.642100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5012b28b89'
down_revision = '65ce37c43657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('meta_data', sa.JSON(), nullable=True, comment='Custom metadata for workspace-level configuration'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'meta_data')
    # ### end Alembic commands ###
