"""fix card model: add meta_data field and align with schemas

Revision ID: f69a0eeedfa8
Revises: 0a5012b28b89
Create Date: 2025-08-23 00:24:19.545261

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f69a0eeedfa8'
down_revision = '0a5012b28b89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Custom metadata for card-level configuration'))
    op.alter_column('cards', 'title',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_comment='Card title',
               existing_nullable=False)
    op.alter_column('cards', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=5000),
               comment='Card description (limited to 5000 chars)',
               existing_comment='Card description (limited to 16KB as per README)',
               existing_nullable=True)
    op.alter_column('cards', 'priority',
               existing_type=sa.SMALLINT(),
               comment='Priority: 1=lowest, 2=low, 3=medium, 4=high, 5=highest',
               existing_comment='Priority: 0=none, 1=low, 2=med, 3=high, 4=urgent',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'priority',
               existing_type=sa.SMALLINT(),
               comment='Priority: 0=none, 1=low, 2=med, 3=high, 4=urgent',
               existing_comment='Priority: 1=lowest, 2=low, 3=medium, 4=high, 5=highest',
               existing_nullable=False)
    op.alter_column('cards', 'description',
               existing_type=sa.String(length=5000),
               type_=sa.TEXT(),
               comment='Card description (limited to 16KB as per README)',
               existing_comment='Card description (limited to 5000 chars)',
               existing_nullable=True)
    op.alter_column('cards', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_comment='Card title',
               existing_nullable=False)
    op.drop_column('cards', 'meta_data')
    # ### end Alembic commands ###
